package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("公司--Company")
public class Company implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "公司类型编号")
	private CompanyType companyType;
	@ApiModelProperty(value = "公司名称")
	private String name;
	@ApiModelProperty(value = "添加时间")
	private String addTime;
	@ApiModelProperty(value = "公司所属人编号")
	private String owerUserId;
	@ApiModelProperty(value = "审核状态")
	private int checkStatus;
	@ApiModelProperty(value = "审核时间")
	private String checkTime;
	@ApiModelProperty(value = "省")
	private String province;
	@ApiModelProperty(value = "市")
	private String city;
	@ApiModelProperty(value = "县")
	private String county;
	@ApiModelProperty(value = "地址")
	private String address;
	@ApiModelProperty(value = "联系人")
	private String lxName;
	@ApiModelProperty(value = "联系电话")
	private String lxTel;
	@ApiModelProperty(value = "公司银行名称")
	private String bankName;
	@ApiModelProperty(value = "公司银行卡号")
	private String bankNo;
	@ApiModelProperty(value = "公司银行账户")
	private String bankAccount;

	public Company() {
	}

	public Company(String id, CompanyType companyType, String name, String owerUserId, int checkStatus) {
		this.id = id;
		this.companyType = companyType;
		this.name = name;
		this.owerUserId = owerUserId;
		this.checkStatus = checkStatus;
	}

	public Company(CompanyType companyType, String name, String addTime, String owerUserId, int checkStatus,
			String checkTime, String province, String city, String county, String address, String lxName, String lxTel,
			String bankName, String bankNo, String bankAccount) {
		this.companyType = companyType;
		this.name = name;
		this.addTime = addTime;
		this.owerUserId = owerUserId;
		this.checkStatus = checkStatus;
		this.checkTime = checkTime;
		this.province = province;
		this.city = city;
		this.county = county;
		this.address = address;
		this.lxName = lxName;
		this.lxTel = lxTel;
		this.bankName = bankName;
		this.bankNo = bankNo;
		this.bankAccount = bankAccount;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "type_id", nullable = false, columnDefinition = "varchar(100) COMMENT '公司类型编号'")
	public CompanyType getCompanyType() {
		return this.companyType;
	}

	public void setCompanyType(CompanyType companyType) {
		this.companyType = companyType;
	}

	@Column(name = "name", nullable = false, columnDefinition = "varchar(50) COMMENT '公司名称'")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "add_time", columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	@Column(name = "ower_user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '公司所属人编号'")
	public String getOwerUserId() {
		return this.owerUserId;
	}

	public void setOwerUserId(String owerUserId) {
		this.owerUserId = owerUserId;
	}

	@Column(name = "check_status", nullable = false, columnDefinition = "int(11) COMMENT '审核状态(0:未审核,1:审核通过,2:审核未通过)'")
	public int getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(int checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "check_time", columnDefinition = "varchar(50) COMMENT '审核时间'")
	public String getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "province", columnDefinition = "varchar(50) COMMENT '省'")
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", columnDefinition = "varchar(50) COMMENT '市'")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", columnDefinition = "varchar(50) COMMENT '县'")
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "address", columnDefinition = "varchar(150) COMMENT '地址'")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "lx_name", columnDefinition = "varchar(30) COMMENT '联系人'")
	public String getLxName() {
		return this.lxName;
	}

	public void setLxName(String lxName) {
		this.lxName = lxName;
	}

	@Column(name = "lx_tel", columnDefinition = "varchar(30) COMMENT '联系电话'")
	public String getLxTel() {
		return this.lxTel;
	}

	public void setLxTel(String lxTel) {
		this.lxTel = lxTel;
	}

	@Column(name = "bank_name", columnDefinition = "varchar(30) COMMENT '公司银行名称'")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_no", columnDefinition = "varchar(30) COMMENT '公司银行卡号'")
	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	@Column(name = "bank_account", columnDefinition = "varchar(50) COMMENT '公司银行账户'")
	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

}
