package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ActSuper generated by hbm2java
 */
@Entity
@Table(name = "feed_back", catalog = "lng")
@ApiModel("意见反馈--FeedBack")
public class FeedBack implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@ApiModelProperty(value = "反馈人编号")
	private User user;
	@ApiModelProperty(value = "反馈类型")
	private String typeName;
	@ApiModelProperty(value = "反馈内容")
	private String content;
	@ApiModelProperty(value = "联系电话")
	private String mobile;
	@ApiModelProperty(value = "已读状态")
	private Integer readStatus;
	@ApiModelProperty(value = "反馈时间")
	private String addTime;

	public FeedBack() {
	}

	

	public FeedBack(User user, String typeName, String content, String mobile, 
			Integer readStatus, String addTime) {
		this.user = user;
		this.typeName = typeName;
		this.content = content;
		this.mobile = mobile;
		this.readStatus = readStatus;
		this.addTime = addTime;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '反馈人编号'")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "type_name", nullable = false, columnDefinition = "varchar(50) COMMENT '反馈类型（1-功能异常,2-体验问题,3-新功能建议,4-其他）'")
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "content", nullable = false, columnDefinition = "varchar(200) COMMENT '反馈内容'")
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "mobile", nullable = false, columnDefinition = "varchar(30) COMMENT '联系电话'")
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "read_status", nullable = false, columnDefinition = "int(11) COMMENT '已读状态（0：未读，1：已读）'")
	public Integer getReadStatus() {
		return readStatus;
	}


	public void setReadStatus(Integer readStatus) {
		this.readStatus = readStatus;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '反馈时间'")
	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

}
