package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GasType generated by hbm2java
 */
@Entity
@Table(name = "gas_type", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("液质类型--GasType")
public class GasType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "液质名称")
	private String name;
	@ApiModelProperty(value = "液质图")
	private String yzImg;
	public GasType() {
	}

	public GasType(String name) {
		this.name = name;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, columnDefinition = "varchar(100) COMMENT '液质名称'")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "yz_img", nullable = false, columnDefinition = "varchar(100) COMMENT '液质图'")
	public String getYzImg() {
		return yzImg;
	}

	public void setYzImg(String yzImg) {
		this.yzImg = yzImg;
	}
}
