package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GasTrade generated by hbm2java
 */
@Entity
@Table(name = "gas_trade", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("燃气买卖--GasTrade")
public class GasTrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "公司编号")
	private Company company;
	@ApiModelProperty(value = "液厂编号")
	private GasFactory gasFactory;
	@ApiModelProperty(value = "液质编号")
	private GasType gasType;
	@ApiModelProperty(value = "主图")
	private String headImg;
	@ApiModelProperty(value = "装载量")
	private int gasVolume;
	@ApiModelProperty(value = "单价")
	private double gasPrice;
	@ApiModelProperty(value = "装车日期")
	private String zcDate;
	@ApiModelProperty(value = "联系人")
	private String lxName;
	@ApiModelProperty(value = "联系电话")
	private String lxTel;
	@ApiModelProperty(value = "配送省份")
	private String psArea;
	@ApiModelProperty(value = "审核状态")
	private int checkStatus;
	@ApiModelProperty(value = "审核时间")
	private String checkTime;
	@ApiModelProperty(value = "上/下架状态")
	private int showStatus;
	@ApiModelProperty(value = "上传人员")
	private String addUserId;
	@ApiModelProperty(value = "添加时间")
	private String addTime;
	@ApiModelProperty(value = "上传人员类型")
	private int userType;
	@ApiModelProperty(value = "热度")
	private int hot;
	@ApiModelProperty(value = "槽车车牌号")
	private String cpNo;
	@ApiModelProperty(value = "挂车车牌号")
	private String gcNo;
	@ApiModelProperty(value = "驾驶员姓名")
	private String jsyName;
	@ApiModelProperty(value = "驾驶员联系方式")
	private String jsyMobile;
	@ApiModelProperty(value = "押运人姓名")
	private String yyrName;
	@ApiModelProperty(value = "押运员联系方式")
	private String yyrMobile;
	@ApiModelProperty(value = "铅封文字信息一")
	private String qfText1;
	@ApiModelProperty(value = "铅封文字信息二")
	private String qfText2;
	@ApiModelProperty(value = "铅封文字信息三")
	private String qfText3;
	@ApiModelProperty(value = "铅封图片信息一")
	private String qfImg1;
	@ApiModelProperty(value = "铅封图片信息二")
	private String qfImg2;
	@ApiModelProperty(value = "铅封图片信息三")
	private String qfImg3;
	@ApiModelProperty(value = "备注")
	private String remark;
	@ApiModelProperty(value = "车辆GPS信息")
	private String gpsInfo;
	@ApiModelProperty(value = "磅单图片")
	private String bdImg;
	@ApiModelProperty(value = "危化品许可证")
	private String whpImg;
	@ApiModelProperty(value = "车辆照片")
	private String tructsImg;
	@ApiModelProperty(value = "确认订单")
	private String tradeOrderId;

	public GasTrade() {
	}

	public GasTrade(Company company, GasFactory gasFactory, GasType gasType, String headImg, int gasVolume,
			double gasPrice, String zcDate, String lxName, String lxTel, String psArea,int checkStatus,
			String checkTime, int showStatus, String addUserId, String addTime, int userType, int hot, String cpNo,
			String gcNo,String jsyName, String jsyMobile, String yyrName, String yyrMobile, String qfText1, String qfText2,
			String qfText3, String qfImg1, String qfImg2, String qfImg3, String remark, String gpsInfo, String bdImg,
			String whpImg, String tructsImg, String tradeOrderId) {
		this.company = company;
		this.gasFactory = gasFactory;
		this.gasType = gasType;
		this.headImg = headImg;
		this.gasVolume = gasVolume;
		this.gasPrice = gasPrice;
		this.zcDate = zcDate;
		this.lxName = lxName;
		this.lxTel = lxTel;
		this.psArea = psArea;
		this.checkStatus = checkStatus;
		this.checkTime = checkTime;
		this.showStatus = showStatus;
		this.addUserId = addUserId;
		this.addTime = addTime;
		this.userType = userType;
		this.hot = hot;
		this.cpNo = cpNo;
		this.gcNo = gcNo;
		this.jsyName = jsyName;
		this.jsyMobile = jsyMobile;
		this.yyrName = yyrName;
		this.yyrMobile = yyrMobile;
		this.qfText1 = qfText1;
		this.qfText2 = qfText2;
		this.qfText3 = qfText3;
		this.qfImg1 = qfImg1;
		this.qfImg2 = qfImg2;
		this.qfImg3 = qfImg3;
		this.remark = remark;
		this.gpsInfo = gpsInfo;
		this.bdImg = bdImg;
		this.whpImg = whpImg;
		this.tructsImg = tructsImg;
		this.tradeOrderId = tradeOrderId;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "company_id", nullable = false, columnDefinition = "varchar(100) COMMENT '公司编号'")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gas_factory_id", nullable = false,columnDefinition = "varchar(100) COMMENT '液厂编号'")
	public GasFactory getGasFactory() {
		return this.gasFactory;
	}

	public void setGasFactory(GasFactory gasFactory) {
		this.gasFactory = gasFactory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gas_type_id", nullable = false,columnDefinition = "varchar(100) COMMENT '液质编号'")
	public GasType getGasType() {
		return this.gasType;
	}

	public void setGasType(GasType gasType) {
		this.gasType = gasType;
	}

	@Column(name = "head_img", nullable = false, length = 100,columnDefinition = "varchar(100) COMMENT '主图'")
	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	@Column(name = "gas_volume", nullable = false,columnDefinition = "varchar(100) COMMENT '装载量'")
	public int getGasVolume() {
		return this.gasVolume;
	}

	public void setGasVolume(int gasVolume) {
		this.gasVolume = gasVolume;
	}

	@Column(name = "gas_price", nullable = false, precision = 10,columnDefinition = "COMMENT '装载量'")
	public double getGasPrice() {
		return this.gasPrice;
	}

	public void setGasPrice(double gasPrice) {
		this.gasPrice = gasPrice;
	}

	@Column(name = "zc_date", columnDefinition = "varchar(50) COMMENT '装车日期'")
	public String getZcDate() {
		return this.zcDate;
	}

	public void setZcDate(String zcDate) {
		this.zcDate = zcDate;
	}

	@Column(name = "lx_name", columnDefinition = "varchar(30) COMMENT '联系人'")
	public String getLxName() {
		return this.lxName;
	}

	public void setLxName(String lxName) {
		this.lxName = lxName;
	}

	@Column(name = "lx_tel", columnDefinition = "varchar(30) COMMENT '联系电话'")
	public String getLxTel() {
		return this.lxTel;
	}

	public void setLxTel(String lxTel) {
		this.lxTel = lxTel;
	}

	@Column(name = "ps_area", columnDefinition = "varchar(200) COMMENT '配送省份（多个逗号隔开）'")
	public String getPsArea() {
		return psArea;
	}

	public void setPsArea(String psArea) {
		this.psArea = psArea;
	}
	
	@Column(name = "check_status", nullable = false, columnDefinition = "int(11) COMMENT '审核状态(0:未审核,1:审核通过,2:审核未通过)'")
	public int getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(int checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "check_time", columnDefinition = "varchar(50) COMMENT '审核时间'")
	public String getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "show_status", nullable = false, columnDefinition = "int(11) COMMENT '上/下架状态（0：上架，1：下架'")
	public int getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(int showStatus) {
		this.showStatus = showStatus;
	}

	@Column(name = "add_user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '上传人员'")
	public String getAddUserId() {
		return this.addUserId;
	}

	public void setAddUserId(String addUserId) {
		this.addUserId = addUserId;
	}

	@Column(name = "add_time", columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	@Column(name = "user_type", nullable = false, columnDefinition = "int(11) COMMENT '上传人员类型（1：后台管理人员，2：普通用户）'")
	public int getUserType() {
		return this.userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	@Column(name = "hot", nullable = false, columnDefinition = "int(11) COMMENT '热度（默认为0）'")
	public int getHot() {
		return this.hot;
	}

	public void setHot(int hot) {
		this.hot = hot;
	}

	@Column(name = "cp_no", columnDefinition = "varchar(50) COMMENT '槽车车牌号'")
	public String getCpNo() {
		return this.cpNo;
	}

	public void setCpNo(String cpNo) {
		this.cpNo = cpNo;
	}

	@Column(name = "jsy_name", columnDefinition = "varchar(50) COMMENT '驾驶员姓名'")
	public String getJsyName() {
		return this.jsyName;
	}

	public void setJsyName(String jsyName) {
		this.jsyName = jsyName;
	}

	@Column(name = "jsy_mobile", columnDefinition = "varchar(50) COMMENT '驾驶员联系方式'")
	public String getJsyMobile() {
		return this.jsyMobile;
	}

	public void setJsyMobile(String jsyMobile) {
		this.jsyMobile = jsyMobile;
	}

	@Column(name = "yyr_name", columnDefinition = "varchar(50) COMMENT '押运人姓名'")
	public String getYyrName() {
		return this.yyrName;
	}

	public void setYyrName(String yyrName) {
		this.yyrName = yyrName;
	}

	@Column(name = "yyr_mobile", columnDefinition = "varchar(50) COMMENT '押运员联系方式'")
	public String getYyrMobile() {
		return this.yyrMobile;
	}

	public void setYyrMobile(String yyrMobile) {
		this.yyrMobile = yyrMobile;
	}

	@Column(name = "qf_text_1", columnDefinition = "varchar(100) COMMENT '铅封文字信息一'")
	public String getQfText1() {
		return this.qfText1;
	}

	public void setQfText1(String qfText1) {
		this.qfText1 = qfText1;
	}

	@Column(name = "qf_text_2", columnDefinition = "varchar(100) COMMENT '铅封文字信息二'")
	public String getQfText2() {
		return this.qfText2;
	}

	public void setQfText2(String qfText2) {
		this.qfText2 = qfText2;
	}

	@Column(name = "qf_text_3", columnDefinition = "varchar(100) COMMENT '铅封文字信息三'")
	public String getQfText3() {
		return this.qfText3;
	}

	public void setQfText3(String qfText3) {
		this.qfText3 = qfText3;
	}

	@Column(name = "qf_img_1", columnDefinition = "varchar(200) COMMENT '铅封图片信息一'")
	public String getQfImg1() {
		return this.qfImg1;
	}

	public void setQfImg1(String qfImg1) {
		this.qfImg1 = qfImg1;
	}

	@Column(name = "qf_img_2", columnDefinition = "varchar(200) COMMENT '铅封图片信息二'")
	public String getQfImg2() {
		return this.qfImg2;
	}

	public void setQfImg2(String qfImg2) {
		this.qfImg2 = qfImg2;
	}

	@Column(name = "qf_img_3", columnDefinition = "varchar(200) COMMENT '铅封图片信息三'")
	public String getQfImg3() {
		return this.qfImg3;
	}

	public void setQfImg3(String qfImg3) {
		this.qfImg3 = qfImg3;
	}

	@Column(name = "remark",columnDefinition = "varchar(255) COMMENT '备注'")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "gps_info",columnDefinition = "varchar(200) COMMENT '车辆GPS信息'")
	public String getGpsInfo() {
		return this.gpsInfo;
	}

	public void setGpsInfo(String gpsInfo) {
		this.gpsInfo = gpsInfo;
	}

	@Column(name = "bd_img", nullable = false, columnDefinition = "varchar(200) COMMENT '磅单图片'")
	public String getBdImg() {
		return this.bdImg;
	}

	public void setBdImg(String bdImg) {
		this.bdImg = bdImg;
	}

	@Column(name = "whp_img", nullable = false, columnDefinition = "varchar(200) COMMENT '危化品许可证'")
	public String getWhpImg() {
		return this.whpImg;
	}

	public void setWhpImg(String whpImg) {
		this.whpImg = whpImg;
	}

	@Column(name = "tructs_img", nullable = false, columnDefinition = "varchar(200) COMMENT '车辆照片'")
	public String getTructsImg() {
		return this.tructsImg;
	}

	public void setTructsImg(String tructsImg) {
		this.tructsImg = tructsImg;
	}

	@Column(name = "trade_order_id",columnDefinition = "varchar(100) COMMENT '确认订单'")
	public String getTradeOrderId() {
		return this.tradeOrderId;
	}

	public void setTradeOrderId(String tradeOrderId) {
		this.tradeOrderId = tradeOrderId;
	}

	@Column(name = "gc_no",columnDefinition = "varchar(100) COMMENT '挂车车牌号'")
	public String getGcNo() {
		return gcNo;
	}

	public void setGcNo(String gcNo) {
		this.gcNo = gcNo;
	}
	
}
