package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GasTradeOrderLog generated by hbm2java
 */
@Entity
@Table(name = "gas_trade_order_log", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("燃气交易订单日志--GasTradeOrderLog")
public class GasTradeOrderLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "燃气交易订单编号")
	private GasTradeOrder gasTradeOrder;
	@ApiModelProperty(value = "订单状态")
	private int orderStatus;
	@ApiModelProperty(value = "详情图片")
	private String orderImgDetail;
	@ApiModelProperty(value = "订单详情文字")
	private String orderDetailTxt;
	@ApiModelProperty(value = "增加时间")
	private String addTime;

	public GasTradeOrderLog() {
	}

	public GasTradeOrderLog(GasTradeOrder gasTradeOrder, int orderStatus, String orderImgDetail,
			String orderDetailTxt, String addTime) {
		this.gasTradeOrder = gasTradeOrder;
		this.orderStatus = orderStatus;
		this.orderImgDetail = orderImgDetail;
		this.orderDetailTxt = orderDetailTxt;
		this.addTime = addTime;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gas_trade_order_id", nullable = false, columnDefinition = "varchar(100) COMMENT '燃气交易订单编号'")
	public GasTradeOrder getGasTradeOrder() {
		return this.gasTradeOrder;
	}

	public void setGasTradeOrder(GasTradeOrder gasTradeOrder) {
		this.gasTradeOrder = gasTradeOrder;
	}

	@Column(name = "order_status", nullable = false, columnDefinition = "int(11) COMMENT '订单状态'")
	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "order_img_detail", columnDefinition = "varchar(100) COMMENT '详情图片'")
	public String getOrderImgDetail() {
		return this.orderImgDetail;
	}

	public void setOrderImgDetail(String orderImgDetail) {
		this.orderImgDetail = orderImgDetail;
	}

	@Column(name = "order_detail_txt", columnDefinition = "varchar(200) COMMENT '订单详情文字'")
	public String getOrderDetailTxt() {
		return this.orderDetailTxt;
	}

	public void setOrderDetailTxt(String orderDetailTxt) {
		this.orderDetailTxt = orderDetailTxt;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '增加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

}
