package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GasTradeImg generated by hbm2java
 */
@Entity
@Table(name = "gas_trade_img", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("燃气买卖其他详图--GasTradeImg")
public class GasTradeImg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "燃气买卖编号")
	private GasTrade gasTrade;
	@ApiModelProperty(value = "其他图片信息")
	private String otherImg;
	@ApiModelProperty(value = "图片顺序")
	private int orderNum;


	public GasTradeImg() {
	}

	public GasTradeImg(GasTrade gasTrade, String otherImg,int orderNum) {
		this.gasTrade = gasTrade;
		this.otherImg = otherImg;
		this.orderNum = orderNum;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "gas_trade_id", nullable = false, columnDefinition = "varchar(100) COMMENT '燃气买卖编号'")
	public GasTrade getGasTrade() {
		return this.gasTrade;
	}

	public void setGasTrade(GasTrade gasTrade) {
		this.gasTrade = gasTrade;
	}

	@Column(name = "other_img", nullable = false, columnDefinition = "varchar(200) COMMENT '其他图片信息'")
	public String getOtherImg() {
		return this.otherImg;
	}

	public void setOtherImg(String otherImg) {
		this.otherImg = otherImg;
	}

	@Column(name = "order_num", nullable = false, columnDefinition = "int(11) COMMENT '图片顺序'")
	public int getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

}
