package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LngInfo generated by hbm2java
 */
@Entity
@Table(name = "gf_support_detail", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("液厂用户点击明细--GfSupportDetail")
public class GfSupportDetail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "液厂编号")
	private GasFactory gf;
	@ApiModelProperty(value = "用户编号")
	private User user;
	@ApiModelProperty(value = "添加时间")
	private String addDate;
	public GfSupportDetail() {
	}

	public GfSupportDetail(GasFactory gf, User user, String addDate) {
		this.gf = gf;
		this.user = user;
		this.addDate = addDate;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gf_id", nullable = false, columnDefinition = "varchar(100) COMMENT '液厂编号'")
	public GasFactory getGf() {
		return gf;
	}
	
	public void setGf(GasFactory gf) {
		this.gf = gf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '前台用户编号'")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "add_date", nullable = false, columnDefinition = "varchar(30) COMMENT '添加时间'")
	public String getAddDate() {
		return this.addDate;
	}

	public void setAddDate(String addDate) {
		this.addDate = addDate;
	}
}
