package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LngInfo generated by hbm2java
 */
@Entity
@Table(name = "lng_info", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("LNG行情--LngInfo")
public class LngInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "液厂编号")
	private GasFactory gasFactory;
	@ApiModelProperty(value = "液质类型")
	private GasType gasType;
	@ApiModelProperty(value = "添加时间")
	private String addDate;
	@ApiModelProperty(value = "显示状态")
	private int showStatus;

	public LngInfo() {
	}

	public LngInfo(GasFactory gasFactory, GasType gasType, String addDate, int showStatus) {
		this.gasFactory = gasFactory;
		this.gasType = gasType;
		this.addDate = addDate;
		this.showStatus = showStatus;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gas_factory_id", nullable = false, columnDefinition = "varchar(100) COMMENT '液厂编号'")
	public GasFactory getGasFactory() {
		return this.gasFactory;
	}

	public void setGasFactory(GasFactory gasFactory) {
		this.gasFactory = gasFactory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "gas_type_id", nullable = false, columnDefinition = "varchar(100) COMMENT '液质类型'")
	public GasType getGasType() {
		return this.gasType;
	}

	public void setGasType(GasType gasType) {
		this.gasType = gasType;
	}

	@Column(name = "add_date", nullable = false, columnDefinition = "varchar(30) COMMENT '添加时间'")
	public String getAddDate() {
		return this.addDate;
	}

	public void setAddDate(String addDate) {
		this.addDate = addDate;
	}

	@Column(name = "show_status", nullable = false, columnDefinition = "int(11) COMMENT '显示状态（0：显示，1：隐藏）'")
	public int getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(int showStatus) {
		this.showStatus = showStatus;
	}

}
