package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;

/**
 * MessageCenter generated by hbm2java
 */
@Entity
@Table(name = "message_center", catalog = "lng")
public class MessageCenter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "主图")
	private String mainImg;
	@ApiModelProperty(value = "标题")
	private String title;
	@ApiModelProperty(value = "内容")
	private String content;
	@ApiModelProperty(value = "显示状态")
	private int showStatus;
	@ApiModelProperty(value = "添加时间")
	private String addTime;
	@ApiModelProperty(value = "消息类型")
	private int messageType;
	@ApiModelProperty(value = "各种消息对应的主键")
	private String primaryId;
	@ApiModelProperty(value = "主键类型")
	private String primaryType;
	@ApiModelProperty(value = "发布人编号")
	private String addUserId;
	@ApiModelProperty(value = "接收人编号")
	private String toUserId;
	@ApiModelProperty(value = "已读状态（0：未读，1：已读）")
	private int readStatus;

	public MessageCenter() {
	}

	
	

	public MessageCenter(String mainImg,String title, String content, int showStatus, String addTime, int messageType,
			String primaryId, String primaryType, String addUserId, String toUserId, int readStatus) {
		this.mainImg = mainImg;
		this.title = title;
		this.content = content;
		this.showStatus = showStatus;
		this.addTime = addTime;
		this.messageType = messageType;
		this.primaryId = primaryId;
		this.primaryType = primaryType;
		this.addUserId = addUserId;
		this.toUserId = toUserId;
		this.readStatus = readStatus;
	}




	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "main_img", columnDefinition = "varchar(150) COMMENT '主图（新闻资讯时存在）'")
	public String getMainImg() {
		return mainImg;
	}

	public void setMainImg(String mainImg) {
		this.mainImg = mainImg;
	}
	
	@Column(name = "title", nullable = false, columnDefinition = "varchar(100) COMMENT '标题'")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = false, columnDefinition = "varchar(65535) COMMENT '内容'")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "show_status", nullable = false, columnDefinition = "int(11) COMMENT '显示状态（0：默认显示，1：隐藏'")
	public int getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(int showStatus) {
		this.showStatus = showStatus;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	@Column(name = "message_type", nullable = false, columnDefinition = "int(11) COMMENT '消息类型（1：新闻资讯，2：系统通知，3：留言回复，4：价格变动通知）'")
	public int getMessageType() {
		return this.messageType;
	}

	public void setMessageType(int messageType) {
		this.messageType = messageType;
	}


	@Column(name = "primary_id", columnDefinition = "varchar(100) COMMENT '各种消息对应的主键'")
	public String getPrimaryId() {
		return primaryId;
	}



	public void setPrimaryId(String primaryId) {
		this.primaryId = primaryId;
	}


	@Column(name = "primary_type", columnDefinition = "varchar(100) COMMENT '主键类型'")
	public String getPrimaryType() {
		return primaryType;
	}



	public void setPrimaryType(String primaryType) {
		this.primaryType = primaryType;
	}


	@Column(name = "add_user_id", columnDefinition = "varchar(100) COMMENT '发布人编号'")
	public String getAddUserId() {
		return addUserId;
	}



	public void setAddUserId(String addUserId) {
		this.addUserId = addUserId;
	}


	@Column(name = "to_user_id", columnDefinition = "varchar(100) COMMENT '接收人编号'")
	public String getToUserId() {
		return toUserId;
	}



	public void setToUserId(String toUserId) {
		this.toUserId = toUserId;
	}


	@Column(name = "read_status", nullable = false, columnDefinition = "int(11) COMMENT '已读状态（0：未读，1：已读）'")
	public int getReadStatus() {
		return readStatus;
	}



	public void setReadStatus(int readStatus) {
		this.readStatus = readStatus;
	}

}
