package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PotTrade generated by hbm2java
 */
@Entity
@Table(name = "pot_trade", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("储罐租卖--PotTrade")
public class PotTrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "公司编号")
	private Company company;
	@ApiModelProperty(value = "装载介质类型编号")
	private PotZzjzType potZzjzType;
	@ApiModelProperty(value = "储罐品牌")
	private TrucksPotPp trucksPotPp;
	@ApiModelProperty(value = "储罐主图")
	private String mainImg;
	@ApiModelProperty(value = "储罐容积")
	private int potVolume;
	@ApiModelProperty(value = "有无手续")
	private String sxInfo;
	@ApiModelProperty(value = "购买年份")
	private String buyYear;
	@ApiModelProperty(value = "罐所在省")
	private String province;
	@ApiModelProperty(value = "罐所在市")
	private String city;
	@ApiModelProperty(value = "租赁价格")
	private double leasePrice;
	@ApiModelProperty(value = "租赁时间单位")
	private String leaseUnit;
	@ApiModelProperty(value = "官方价格")
	private double sellPrice;
	@ApiModelProperty(value = "备注")
	private String remark;
	@ApiModelProperty(value = "联系人")
	private String lxName;
	@ApiModelProperty(value = "联系电话")
	private String lxTel;
	@ApiModelProperty(value = "审核状态")
	private int checkStatus; 
	@ApiModelProperty(value = "审核时间")
	private String checkTime;
	@ApiModelProperty(value = "上/下架状态")
	private int showStatus;
	@ApiModelProperty(value = "上传人员")
	private String addUserId;
	@ApiModelProperty(value = "添加时间")
	private String addTime;
	@ApiModelProperty(value = "上传人员类型")
	private int userType;
	@ApiModelProperty(value = "热度")
	private int hot;
	@ApiModelProperty(value = "租卖类型")
	private int tradeStatus;

	public PotTrade() {
	}

	public PotTrade(Company company, PotZzjzType potZzjzType, TrucksPotPp trucksPotPp, String mainImg,
			int potVolume, String sxInfo, String buyYear, String province, String city, double leasePrice,
			String leaseUnit,double sellPrice, String remark, String lxName, String lxTel, int checkStatus, String checkTime,
			int showStatus, String addUserId, String addTime, int userType, int hot, int tradeStatus) {
		this.company = company;
		this.potZzjzType = potZzjzType;
		this.trucksPotPp = trucksPotPp;
		this.mainImg = mainImg;
		this.potVolume = potVolume;
		this.sxInfo = sxInfo;
		this.buyYear = buyYear;
		this.province = province;
		this.city = city;
		this.leasePrice = leasePrice;
		this.leaseUnit = leaseUnit;
		this.sellPrice = sellPrice;
		this.remark = remark;
		this.lxName = lxName;
		this.lxTel = lxTel;
		this.checkStatus = checkStatus;
		this.checkTime = checkTime;
		this.showStatus = showStatus;
		this.addUserId = addUserId;
		this.addTime = addTime;
		this.userType = userType;
		this.hot = hot;
		this.tradeStatus = tradeStatus;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "company_id", nullable = false, columnDefinition = "varchar(100) COMMENT '公司编号'")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "zzjz_type_id", nullable = false, columnDefinition = "varchar(100) COMMENT '装载介质类型编号'")
	public PotZzjzType getPotZzjzType() {
		return this.potZzjzType;
	}

	public void setPotZzjzType(PotZzjzType potZzjzType) {
		this.potZzjzType = potZzjzType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pot_pp_id", nullable = false, columnDefinition = "varchar(100) COMMENT '储罐品牌'")
	public TrucksPotPp getTrucksPotPp() {
		return this.trucksPotPp;
	}

	public void setTrucksPotPp(TrucksPotPp trucksPotPp) {
		this.trucksPotPp = trucksPotPp;
	}

	@Column(name = "main_img", nullable = false, columnDefinition = "varchar(100) COMMENT '储罐主图'")
	public String getMainImg() {
		return this.mainImg;
	}

	public void setMainImg(String mainImg) {
		this.mainImg = mainImg;
	}

	@Column(name = "pot_volume", nullable = false, columnDefinition = "int(11) COMMENT '储罐容积'")
	public int getPotVolume() {
		return this.potVolume;
	}

	public void setPotVolume(int potVolume) {
		this.potVolume = potVolume;
	}

	@Column(name = "sx_info", nullable = false, columnDefinition = "int(11) COMMENT '有无手续(1:有，2:无)'")
	public String getSxInfo() {
		return this.sxInfo;
	}

	public void setSxInfo(String sxInfo) {
		this.sxInfo = sxInfo;
	}

	@Column(name = "buy_year", nullable = false, columnDefinition = "varchar(30) COMMENT '购买年份'")
	public String getBuyYear() {
		return this.buyYear;
	}

	public void setBuyYear(String buyYear) {
		this.buyYear = buyYear;
	}

	@Column(name = "province", nullable = false, columnDefinition = "varchar(50) COMMENT '罐所在省'")
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", nullable = false, columnDefinition = "varchar(50) COMMENT '罐所在市'")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "lease_price", nullable = false, precision = 10, columnDefinition = "COMMENT '租赁价格'")
	public double getLeasePrice() {
		return this.leasePrice;
	}

	public void setLeasePrice(double leasePrice) {
		this.leasePrice = leasePrice;
	}

	@Column(name = "lease_unit", columnDefinition = "varchar(30) COMMENT '租赁时间单位（每年/月/日）'")
	public String getLeaseUnit() {
		return leaseUnit;
	}

	public void setLeaseUnit(String leaseUnit) {
		this.leaseUnit = leaseUnit;
	}

	@Column(name = "sell_price", nullable = false, precision = 10, columnDefinition = "COMMENT '官方价格'")
	public double getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(double sellPrice) {
		this.sellPrice = sellPrice;
	}

	@Column(name = "remark", columnDefinition = "varchar(255) COMMENT '备注'")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "lx_name", columnDefinition = "varchar(30) COMMENT '联系人'")
	public String getLxName() {
		return this.lxName;
	}

	public void setLxName(String lxName) {
		this.lxName = lxName;
	}

	@Column(name = "lx_tel", columnDefinition = "varchar(30) COMMENT '联系电话'")
	public String getLxTel() {
		return this.lxTel;
	}

	public void setLxTel(String lxTel) {
		this.lxTel = lxTel;
	}

	@Column(name = "check_status", nullable = false, columnDefinition = "int(11) COMMENT '审核状态(0:未审核,1:审核通过,2:审核未通过)'")
	public int getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(int checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "check_time", columnDefinition = "varchar(50) COMMENT '审核时间'")
	public String getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(String checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "show_status", nullable = false, columnDefinition = "int(11) COMMENT '上/下架状态（0：上架，1：下架）'")
	public int getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(int showStatus) {
		this.showStatus = showStatus;
	}

	@Column(name = "add_user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '上传人员'")
	public String getAddUserId() {
		return this.addUserId;
	}

	public void setAddUserId(String addUserId) {
		this.addUserId = addUserId;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	@Column(name = "user_type", nullable = false, columnDefinition = "int(11) COMMENT '上传人员类型（1：后台管理人员，2：普通用户）'")
	public int getUserType() {
		return this.userType;
	}

	public void setUserType(int userType) {
		this.userType = userType;
	}

	@Column(name = "hot", nullable = false, columnDefinition = "int(11) COMMENT '热度（默认为0）'")
	public int getHot() {
		return this.hot;
	}

	public void setHot(int hot) {
		this.hot = hot;
	}

	@Column(name = "trade_status", nullable = false, columnDefinition = "int(11) COMMENT '租卖类型(0:可租可卖,1:租,2:卖)'")
	public int getTradeStatus() {
		return this.tradeStatus;
	}

	public void setTradeStatus(int tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

}
