package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SystemInfo generated by hbm2java
 */
@Entity
@Table(name = "system_info", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("系统配置信息--SystemInfo")
public class SystemInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "APPID")
	private String appId;
	@ApiModelProperty(value = "APPSECRET")
	private String appSecret;
	@ApiModelProperty(value = "水印")
	private String waterMark;

	public SystemInfo() {
	}

	public SystemInfo(String appId, String appSecret, String waterMark) {
		this.appId = appId;
		this.appSecret = appSecret;
		this.waterMark = waterMark;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "app_id", nullable = false, columnDefinition = "varchar(50) COMMENT 'APPID'")
	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	@Column(name = "app_secret", nullable = false, columnDefinition = "varchar(100) COMMENT 'APPSECRET'")
	public String getAppSecret() {
		return this.appSecret;
	}

	public void setAppSecret(String appSecret) {
		this.appSecret = appSecret;
	}

	@Column(name = "water_mark", columnDefinition = "varchar(50) COMMENT '水印'")
	public String getWaterMark() {
		return this.waterMark;
	}

	public void setWaterMark(String waterMark) {
		this.waterMark = waterMark;
	}

}
