package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrucksHeadType generated by hbm2java
 */
@Entity
@Table(name = "trucks_head_type", catalog = "lng")
public class TrucksHeadType implements java.io.Serializable {

	private String id;
	private String name;
	private Set<TrucksTrade> trucksTrades = new HashSet<TrucksTrade>(0);

	public TrucksHeadType() {
	}

	public TrucksHeadType(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public TrucksHeadType(String id, String name, Set<TrucksTrade> trucksTrades) {
		this.id = id;
		this.name = name;
		this.trucksTrades = trucksTrades;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trucksHeadType")
	public Set<TrucksTrade> getTrucksTrades() {
		return this.trucksTrades;
	}

	public void setTrucksTrades(Set<TrucksTrade> trucksTrades) {
		this.trucksTrades = trucksTrades;
	}

}
