package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserFocus generated by hbm2java
 */
@Entity
@Table(name = "user_focus", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel(" 用户关注--UserFocus")
public class UserFocus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value="用户编号")
	private User user;
	@ApiModelProperty(value = "关注编号")
	private String focusId;
	@ApiModelProperty(value = "关注类型")
	private String focusType;
	@ApiModelProperty(value = "关注时间")
	private String focusTime;

	public UserFocus() {
	}

	public UserFocus( User user, String focusId, String focusType, String focusTime) {
		this.user = user;
		this.focusId = focusId;
		this.focusType = focusType;
		this.focusTime = focusTime;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "user_id", nullable = false,columnDefinition = "varchar(100) COMMENT '用户编号")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "focus_id", nullable = false,columnDefinition = "varchar(100) COMMENT '关注编号")
	public String getFocusId() {
		return this.focusId;
	}

	public void setFocusId(String focusId) {
		this.focusId = focusId;
	}

	@Column(name = "focus_type", nullable = false,columnDefinition = "varchar(20) COMMENT '关注类型")
	public String getFocusType() {
		return this.focusType;
	}

	public void setFocusType(String focusType) {
		this.focusType = focusType;
	}

	@Column(name = "focus_time", nullable = false,columnDefinition = "varchar(50) COMMENT '关注时间")
	public String getFocusTime() {
		return this.focusTime;
	}

	public void setFocusTime(String focusTime) {
		this.focusTime = focusTime;
	}

}
