package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LngMessageUserZc generated by hbm2java
 */
@Entity
@Table(name = "lng_message_user_zc", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("LNG行情留言支持明细--LngMessageUserZc")
public class LngMessageUserZc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "消息编号")
	private LngMessage lngMessage;
	@ApiModelProperty(value = "用户编号")
	private User user;
	@ApiModelProperty(value = "添加时间")
	private String addTime;

	public LngMessageUserZc() {
	}

	public LngMessageUserZc(LngMessage lngMessage, User user, String addTime) {
		this.lngMessage = lngMessage;
		this.user = user;
		this.addTime = addTime;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "message_id", nullable = false, columnDefinition = "varchar(100) COMMENT '消息编号'")
	public LngMessage getLngMessage() {
		return this.lngMessage;
	}

	public void setLngMessage(LngMessage lngMessage) {
		this.lngMessage = lngMessage;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false, columnDefinition = "varchar(100) COMMENT '用户编号'")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(100) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

}
