package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ActSuper generated by hbm2java
 */
@Entity
@Table(name = "act_super", catalog = "lng")
@ApiModel("用户动作--ActSuper")
public class ActSuper implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@ApiModelProperty(value = "动作编号")
	private ModuleAct moduleAct;
	@ApiModelProperty(value = "后台用户编号")
	private SuperUser superUser;
	@ApiModelProperty(value = "添加时间")
	private String addTime;

	public ActSuper() {
	}

	public ActSuper(ModuleAct moduleAct, SuperUser superUser, String addTime) {
		this.moduleAct = moduleAct;
		this.superUser = superUser;
		this.addTime = addTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "act_id", nullable = false, columnDefinition = "varchar(100) COMMENT '动作编号'")
	public ModuleAct getModuleAct() {
		return this.moduleAct;
	}

	public void setModuleAct(ModuleAct moduleAct) {
		this.moduleAct = moduleAct;
	}

	@ManyToOne(fetch = FetchType.EAGER)//等同于lazy="false"
	@JoinColumn(name = "super_id", nullable = false, columnDefinition = "varchar(100) COMMENT '后台用户编号'")
	public SuperUser getSuperUser() {
		return this.superUser;
	}

	public void setSuperUser(SuperUser superUser) {
		this.superUser = superUser;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(100) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

}
