package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LngPriceDetail generated by hbm2java
 */
@Entity
@Table(name = "lng_price_detail", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("燃气价格详情--LngPriceDetail")
public class LngPriceDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "lng编号")
	private LngInfo lngInfo;
	@ApiModelProperty(value = "价格")
	private int price;
	@ApiModelProperty(value = "价格时间")
	private String priceTime;
	@ApiModelProperty(value = "备注")
	private String remark;
	@ApiModelProperty(value = "添加时间")
	private String addTime;

	public LngPriceDetail() {
	}

	public LngPriceDetail(LngInfo lngInfo, int price, String priceTime, String remark, String addTime) {
		this.lngInfo = lngInfo;
		this.price = price;
		this.priceTime = priceTime;
		this.remark = remark;
		this.addTime = addTime;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "lng_id", nullable = false, columnDefinition = "varchar(100) COMMENT 'lng编号'")
	public LngInfo getLngInfo() {
		return this.lngInfo;
	}

	public void setLngInfo(LngInfo lngInfo) {
		this.lngInfo = lngInfo;
	}

	@Column(name = "price", nullable = false, columnDefinition = "int(11) COMMENT '价格'")
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "price_time", nullable = false, columnDefinition = "varchar(50) COMMENT '价格时间'")
	public String getPriceTime() {
		return this.priceTime;
	}

	public void setPriceTime(String priceTime) {
		this.priceTime = priceTime;
	}

	@Column(name = "remark", columnDefinition = "varchar(100) COMMENT '备注'")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

}
