package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PotTradeImg generated by hbm2java
 */
@Entity
@Table(name = "pot_trade_img", catalog = "lng")
@GenericGenerator(name = "system-uuid", strategy = "org.hibernate.id.UUIDGenerator")
@ApiModel("储罐租卖详情图--PotTradeImg")
public class PotTradeImg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "储罐买卖编号")
	private PotTrade potTrade;
	@ApiModelProperty(value = "储罐详情图")
	private String potDetailImg;

	public PotTradeImg() {
	}

	public PotTradeImg(PotTrade potTrade, String potDetailImg) {
		this.potTrade = potTrade;
		this.potDetailImg = potDetailImg;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pot_trade_id", nullable = false, columnDefinition = "varchar(100) COMMENT '储罐买卖编号'")
	public PotTrade getPotTrade() {
		return this.potTrade;
	}

	public void setPotTrade(PotTrade potTrade) {
		this.potTrade = potTrade;
	}

	@Column(name = "pot_detail_img", nullable = false, columnDefinition = "varchar(100) COMMENT '储罐详情图'")
	public String getPotDetailImg() {
		return this.potDetailImg;
	}

	public void setPotDetailImg(String potDetailImg) {
		this.potDetailImg = potDetailImg;
	}

}
