package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrucksPotPp generated by hbm2java
 */
@Entity
@Table(name = "trucks_pot_pp", catalog = "lng")
public class TrucksPotPp implements java.io.Serializable {

	private String id;
	private String name;
	private Set<PotTrade> potTrades = new HashSet<PotTrade>(0);

	public TrucksPotPp() {
	}

	public TrucksPotPp(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public TrucksPotPp(String id, String name, Set<PotTrade> potTrades) {
		this.id = id;
		this.name = name;
		this.potTrades = potTrades;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trucksPotPp")
	public Set<PotTrade> getPotTrades() {
		return this.potTrades;
	}

	public void setPotTrades(Set<PotTrade> potTrades) {
		this.potTrades = potTrades;
	}

}
