package com.lng.pojo;
// Generated 2019-12-2 10:34:35 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModelProperty;

/**
 * MessageCenter generated by hbm2java
 */
@Entity
@Table(name = "message_center", catalog = "lng")
public class MessageCenter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	@ApiModelProperty(value = "标题")
	private String title;
	@ApiModelProperty(value = "内容")
	private String content;
	@ApiModelProperty(value = "显示状态")
	private int showStatus;
	@ApiModelProperty(value = "添加时间")
	private String addTime;
	@ApiModelProperty(value = "消息类型")
	private int messageType;
	@ApiModelProperty(value = "申请人编号")
	private String applyUserId;
	@ApiModelProperty(value = "接收人编号")
	private String acceptUserId;
	@ApiModelProperty(value = "燃气买卖编号")
	private String gasTradeId;
	@ApiModelProperty(value = "燃气买卖订单号")
	private String gradeTradeOrder;
	@ApiModelProperty(value = "审核状态")
	private int checkStatus;

	public MessageCenter() {
	}

	public MessageCenter(String id, String title, String content, int showStatus, String addTime, int messageType,
			String applyUserId, String acceptUserId, String gasTradeId, int checkStatus,String gradeTradeOrder) {
		this.title = title;
		this.content = content;
		this.showStatus = showStatus;
		this.addTime = addTime;
		this.messageType = messageType;
		this.applyUserId = applyUserId;
		this.acceptUserId = acceptUserId;
		this.gasTradeId = gasTradeId;
		this.checkStatus = checkStatus;
		this.gradeTradeOrder = gradeTradeOrder;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@Column(name = "id", unique = true, nullable = false, length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, columnDefinition = "varchar(100) COMMENT '标题'")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", nullable = false, columnDefinition = "varchar(65535) COMMENT '内容'")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "show_status", nullable = false, columnDefinition = "int(11) COMMENT '显示状态（0：默认显示，1：隐藏'")
	public int getShowStatus() {
		return this.showStatus;
	}

	public void setShowStatus(int showStatus) {
		this.showStatus = showStatus;
	}

	@Column(name = "add_time", nullable = false, columnDefinition = "varchar(50) COMMENT '添加时间'")
	public String getAddTime() {
		return this.addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	@Column(name = "message_type", nullable = false, columnDefinition = "int(11) COMMENT '消息类型'")
	public int getMessageType() {
		return this.messageType;
	}

	public void setMessageType(int messageType) {
		this.messageType = messageType;
	}

	@Column(name = "apply_user_id", columnDefinition = "varchar(100) COMMENT '申请人编号（类型4时存在'")
	public String getApplyUserId() {
		return this.applyUserId;
	}

	public void setApplyUserId(String applyUserId) {
		this.applyUserId = applyUserId;
	}

	@Column(name = "accept_user_id", columnDefinition = "varchar(100) COMMENT '接收人编号（类型为4时存在）'")
	public String getAcceptUserId() {
		return this.acceptUserId;
	}

	public void setAcceptUserId(String acceptUserId) {
		this.acceptUserId = acceptUserId;
	}

	@Column(name = "gas_trade_id", columnDefinition = "varchar(100) COMMENT '燃气买卖编号（类型为5时存在）'")
	public String getGasTradeId() {
		return this.gasTradeId;
	}

	public void setGasTradeId(String gasTradeId) {
		this.gasTradeId = gasTradeId;
	}

	@Column(name = "check_status", nullable = false, columnDefinition = "int(11) COMMENT '审核状态'")
	public int getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(int checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "grade_trade_order_id", columnDefinition = "varchar(100) COMMENT '燃气买卖订单号（类型为5时存在）'")
	public String getGradeTradeOrder() {
		return gradeTradeOrder;
	}

	public void setGradeTradeOrder(String gradeTradeOrder) {
		this.gradeTradeOrder = gradeTradeOrder;
	}

}
